### ISSUE TITLE
在windows powershell执行报错

### ISSUE THREAD

**Issue by cl1107** [YunYouJun/nnrm#7]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/21985353/155289751-15348e49-41a4-489e-9075-0c156f16a5fd.png">
PS D:\aboutWork\APEX\R5\r5-customer> nnrm ls
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:424:7)
    at file:///D:/aboutDownload/softWare/nvm/v14.17.4/node_modules/nnrm/utils/registries.js:7:19
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
PS D:\aboutWork\APEX\R5\r5-customer>

**Comment by YunYouJun** [comment]
抱歉，本仓库并未适配 Windows 环境（我是 mac 我也不知道怎么适配），因此 Windows 下请使用 Bash 终端。

**Comment by cl1107** [comment]
> 抱歉，本仓库并未适配 Windows 环境（我是 mac 我也不知道怎么适配），因此 Windows 下请使用 Bash 终端。

我提交了一个pr，你看看吧，没问题麻烦你合并发个版本，scripts里几个test我都跑了都可以

**Comment by YunYouJun** [comment]
Thanks. Released in `v0.3.5`. #8
